<a href="https://www.kaggle.com/code/emmanuelniyioriolowo/data-cleaning-exploration?scriptVersionId=283439161" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# import packages
import numpy as np 
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/ncdc-lassa-fever-timeseries-20202025/lassa_fever_timeseries_minimal.csv
/kaggle/input/ncdc-lassa-fever-timeseries-20202025/lassa_fever_timeseries_full.csv

## Cleaning

In [2]:
# read data into a dataframe
df = pd.read_csv('/kaggle/input/ncdc-lassa-fever-timeseries-20202025/lassa_fever_timeseries_minimal.csv')
df

,week_start_date,week_end_date,epi_year,epi_week,suspected_cases,confirmed_cases,deaths
0,2019-12-30,2020-01-05,2020,1,98,18,2
1,2020-01-06,2020-01-12,2020,2,158,64,12
2,2020-01-13,2020-01-19,2020,3,159,81,10
3,2020-01-20,2020-01-26,2020,4,318,95,19
4,2020-01-27,2020-02-02,2020,5,531,104,6
...,...,...,...,...,...,...,...
302,2025-10-13,2025-10-19,2025,42,116,9,1
303,2025-10-20,2025-10-26,2025,43,97,11,1
304,2025-10-27,2025-11-02,2025,44,94,12,1
305,2025-11-03,2025-11-09,2025,45,84,10,1
306,2025-11-10,2025-11-16,2025,46,123,19,6

In [3]:
# construct series dataframe
ts_data = df[['week_end_date', 'confirmed_cases']].copy()
ts_data.columns = ['date', 'confirmed_cases']
ts_data

           date  confirmed_cases
0    2020-01-05               18
1    2020-01-12               64
2    2020-01-19               81
3    2020-01-26               95
4    2020-02-02              104
..          ...              ...
302  2025-10-19                9
303  2025-10-26               11
304  2025-11-02               12
305  2025-11-09               10
306  2025-11-16               19

[307 rows x 2 columns]

In [4]:
# create and display plot 
fig =  px.line(ts_data, x="date", y="confirmed_cases",
        title="Weekly Lassa Fever Cases (2020–2025)")
fig.show()